// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB97_EfkT3xh6HOGf8xxxuh3bv1NEiM09A',
    appId: '1:700340873158:web:124122ade37ed65a1a34c7',
    messagingSenderId: '700340873158',
    projectId: 'megogo-prototype',
    authDomain: 'megogo-prototype.firebaseapp.com',
    storageBucket: 'megogo-prototype.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7O4Ldi_oTIng2B6wjacbEqtYNjhMPF0Y',
    appId: '1:700340873158:android:028435fd6238853e1a34c7',
    messagingSenderId: '700340873158',
    projectId: 'megogo-prototype',
    storageBucket: 'megogo-prototype.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu9ppkZxsMkmc8qaezwjpZYbtb4RmiZvY',
    appId: '1:700340873158:ios:32271f11eb2f932c1a34c7',
    messagingSenderId: '700340873158',
    projectId: 'megogo-prototype',
    storageBucket: 'megogo-prototype.appspot.com',
    iosBundleId: 'com.example.megogoPrototype',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu9ppkZxsMkmc8qaezwjpZYbtb4RmiZvY',
    appId: '1:700340873158:ios:32271f11eb2f932c1a34c7',
    messagingSenderId: '700340873158',
    projectId: 'megogo-prototype',
    storageBucket: 'megogo-prototype.appspot.com',
    iosBundleId: 'com.example.megogoPrototype',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB97_EfkT3xh6HOGf8xxxuh3bv1NEiM09A',
    appId: '1:700340873158:web:fbf89c73325c56261a34c7',
    messagingSenderId: '700340873158',
    projectId: 'megogo-prototype',
    authDomain: 'megogo-prototype.firebaseapp.com',
    storageBucket: 'megogo-prototype.appspot.com',
  );
}
